version: "3"

services:
  mybunker:
    image: bunkerity/bunkerweb:1.5.0
    ports:
      - 80:8080
      - 443:8443
    environment:
      SERVER_NAME: "www.example.com" # replace with your domain
      API_WHITELIST_IP: "127.0.0.0/8 10.20.30.0/24"
      SERVE_FILES: "no"
      DISABLE_DEFAULT_SERVER: "yes"
      AUTO_LETS_ENCRYPT: "yes"
      USE_CLIENT_CACHE: "yes"
      USE_GZIP: "yes"
      MAX_CLIENT_SIZE: "50m"
      USE_REVERSE_PROXY: "yes"
      REVERSE_PROXY_URL: "/"
      REVERSE_PROXY_HOST: "http://myps"
      # Onces the installation is done, you can remove these lines
      LIMIT_REQ_URL_1: "/install/index.php"
      LIMIT_REQ_RATE_1: "8r/s"
    labels:
      - "bunkerweb.INSTANCE" # required for the scheduler to recognize the container
    networks:
      - bw-universe
      - bw-services

  bw-scheduler:
    image: bunkerity/bunkerweb-scheduler:1.5.0
    depends_on:
      - mybunker
    environment:
      DOCKER_HOST: "tcp://bw-docker-proxy:2375"
    volumes:
      - bw-data:/data
    networks:
      - bw-universe
      - bw-docker

  bw-docker-proxy:
    image: tecnativa/docker-socket-proxy:0.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINERS=1
    networks:
      - bw-docker

  myps:
    image: prestashop/prestashop:1.7
    volumes:
      - ps-data:/var/www/html
    environment:
      - DB_SERVER=mydb
      - DB_USER=user
      - DB_PASSWD=db-user-pwd # replace with a stronger password (must match MYSQL_PASSWORD)
      - DB_PREFIX=prefix_ # replace with a random prefix (good security practice)
      - DB_NAME=prestashop
      - PS_ENABLE_SSL=1
      - ADMIN_MAIL=admin@example.com # change to the prestashop admin email
      - ADMIN_PASSWD=changeme # change to the prestashop admin password
      - PS_FOLDER_ADMIN=administration # change to the prestashop admin folder
    networks:
      - bw-services

  mydb:
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      bw-services:
        aliases:
          - mydb
    environment:
      - MYSQL_ROOT_PASSWORD=db-root-pwd # replace with a stronger password
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=user
      - MYSQL_PASSWORD=db-user-pwd # replace with a stronger password (must match DB_PASSWD)

volumes:
  bw-data:
  ps-data:
  db-data:

networks:
  bw-universe:
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24
  bw-services:
  bw-docker:
